In [1]:
import sys  # Always needed
print("Python version:", sys.version)
import pandas as pd
print("pandas version:", pd.__version__)
import matplotlib
print("matplotlib version:", matplotlib.__version__)
import numpy as np
print("NumPy version:", np.__version__)
import scipy as sp
print("SciPy version:", sp.__version__)
import IPython
print("IPython version:", IPython.__version__)
import sklearn
print("scikit-learn version:", sklearn.__version__)
import mglearn
import os

Python version: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
pandas version: 1.1.3
matplotlib version: 3.3.2
NumPy version: 1.19.2
SciPy version: 1.5.2
IPython version: 7.19.0
scikit-learn version: 0.23.2


In [2]:

dataset = pd.read_csv("Files\season-1718_csv.csv", parse_dates=["Date"], usecols=['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR'])
dataset.iloc[:5]

team_names = {'Manchester City': 0, 'Manchester United': 1, 'Tottenham Hotspur': 2, 'Liverpool': 3, 'Chelsea': 4, 'Arsenal': 5, 'Burnley': 6, 'Everton': 7, 'Leicester City': 8, 'Newcastle': 9, 'Crystal Palace': 10, 'Bournemouth': 11, 'West Ham': 12, 'Watford': 13, 'Brighton': 14, 'Huddersfield': 15, 'Southampton': 16, 'Swansea': 17, 'Stoke City': 18, 'West Brom': 19}

feature_names = ['HomeTeam', 'AwayTeam','HomeLastResult', 'AwayLastResult']
target_names = {'H': 2, 'D': 1, 'A': 0}


In [3]:

# Creating two new features determining whether each team won their last match.
from collections import defaultdict

last_result = defaultdict(lambda: -1)

dataset["HomeLastResult"] = -1
dataset["AwayLastResult"] = -1

for index, row in dataset.iterrows():
    home_team = row['HomeTeam']
    away_team = row['AwayTeam']
    row['FTR'] = target_names[row['FTR']]
    row['HomeTeam'] = team_names[home_team]
    row['AwayTeam'] = team_names[away_team] 
    dataset.iloc[index] = row


0     -1
1     -1
2     -1
3     -1
4     -1
      ..
375   -1
376   -1
377   -1
378   -1
379   -1
Name: HomeLastResult, Length: 380, dtype: int64

In [4]:
for index, row in dataset.iterrows():
    home_team = row['HomeTeam']
    away_team = row['AwayTeam']  
    row['HomeLastResult'] = last_result[home_team]
    row['AwayLastResult'] = last_result[away_team]  
    dataset.iloc[index] = row
    if row['FTR'] == 2:
        last_result[home_team] = 2
        last_result[away_team] = 0
    elif row['FTR'] == 0:
        last_result[home_team] = 0
        last_result[away_team] = 2
    elif row['FTR'] == 1:
        last_result[home_team] = 1
        last_result[away_team] = 1
    else:
        last_result[home_team] = -1
        last_result[away_team] = -1
        
        
 # needs to be not but we have 3 classes not true/false
  
    #myrow = dataset.loc[[index]]
    #display(myrow)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(dataset[feature_names].values, dataset['FTR'].values, shuffle=False, random_state = 5)
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

X_train[0:20]


X_train shape: (285, 4)
y_train shape: (285,)


array([[5, 8, -1, -1],
       [14, 0, -1, -1],
       [4, 6, -1, -1],
       [10, 15, -1, -1],
       [7, 18, -1, -1],
       [16, 17, -1, -1],
       [13, 3, -1, -1],
       [19, 11, -1, -1],
       [1, 12, -1, -1],
       [9, 2, -1, -1],
       [11, 13, 0, 1],
       [6, 19, 2, 2],
       [8, 14, 0, 0],
       [3, 10, 1, 0],
       [16, 12, 1, 0],
       [18, 5, 0, 2],
       [17, 1, 1, 2],
       [15, 9, 2, 0],
       [2, 4, 2, 0],
       [0, 7, 2, 2]], dtype=object)

In [7]:
y_train[0:20]
y_train = y_train.astype('int')
y_train

array([2, 0, 0, 0, 2, 1, 1, 2, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 1, 0, 0,
       1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 0, 2, 2, 0, 1, 1,
       2, 1, 0, 1, 1, 2, 1, 2, 0, 2, 0, 0, 0, 0, 2, 2, 1, 0, 0, 2, 2, 1,
       2, 2, 0, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 0, 2, 2, 2, 2, 2, 0, 0,
       0, 2, 2, 0, 1, 2, 2, 0, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2, 2, 2, 2,
       2, 2, 2, 1, 0, 2, 2, 0, 2, 1, 1, 2, 1, 2, 0, 1, 1, 0, 0, 2, 1, 2,
       0, 1, 2, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 0,
       2, 2, 2, 1, 0, 1, 2, 2, 0, 1, 2, 0, 0, 0, 2, 1, 2, 1, 2, 0, 2, 0,
       0, 0, 0, 2, 1, 2, 0, 1, 1, 2, 1, 2, 1, 0, 1, 2, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 1, 2, 1, 1, 0, 1, 1, 1, 0, 0, 2, 0, 2, 0, 0, 2, 1, 1,
       1, 2, 0, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2, 2, 2, 1, 1, 2, 0, 2,
       1, 0, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 0, 1, 1, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 0, 2, 1, 2, 1, 1, 2, 2, 0, 0, 2, 0, 2, 1, 2, 1, 2])

In [8]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=32)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
# Using the team names and both team's last result as features.
print("Test set score:  {:.2f}".format(np.mean(y_pred == y_test)))

Test set score:  0.61


# New Feature: Wins so far?

In [9]:
dataset["HomeWinsSoFar"], dataset["AwayWinsSoFar"] = 0, 0
wins_so_far = defaultdict(int)
feature_names.extend(("HomeWinsSoFar", "AwayWinsSoFar"))

In [10]:
feature_names

['HomeTeam',
 'AwayTeam',
 'HomeLastResult',
 'AwayLastResult',
 'HomeWinsSoFar',
 'AwayWinsSoFar']

In [11]:
for index, row in dataset.iterrows():
    home_team = row["HomeTeam"]
    away_team = row["AwayTeam"]
    row["HomeWinsSoFar"] = wins_so_far[home_team]
    row["AwayWinsSoFar"] = wins_so_far[away_team]
    
    dataset.iloc[index] = row
    if row['FTR'] == 2:
        wins_so_far[home_team] += 1
    elif row['FTR'] == 0:
        wins_so_far[away_team] += 1
    else:
        continue
    if row["HomeTeam"] == 2 or row["AwayTeam"] == 2:    
        myrow = dataset.loc[[index]]
        display(myrow)
#dataset[0:80]

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
9 2017-08-13        9        2     0     2   0              -1   

   AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
9              -1              0              0

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
18 2017-08-20        2        4     1     2   0               2   

    AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
18               0              1              0

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
32 2017-09-09        7        2     0     3   0               0   

    AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
32               1              1              1

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
57 2017-09-23       12        2     2     3   0               1   

    AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
57               1              1              2

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
62 2017-09-30       15        2     0     4   0               1   

    AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
62               2              2              3

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
75 2017-10-14        2       11     1     0   2               2   

    AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
75               1              4              1

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
89 2017-10-22        2        3     4     1   2               2   

    AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
89               1              5              3

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
94 2017-10-28        1        2     1     0   2               0   

    AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
94               2              6              6

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
109 2017-05-11        2       10     1     0   2               0   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
109               1              6              1

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
110 2017-11-18        5        2     2     0   2               0   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
110               2              6              7

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
131 2017-11-28        8        2     2     1   2               1   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
131               1              3              7

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
155 2017-09-12        2       18     5     1   2               1   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
155               2              7              4

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
168 2017-12-13        2       14     2     0   2               2   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
168               0              8              4

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
174 2017-12-16        0        2     4     1   2               2   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
174               2             16              9

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
182 2017-12-23        6        2     0     3   0               1   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
182               0              9              9

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
195 2017-12-26        2       16     5     2   2               2   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
195               1             10              4

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
216 2018-02-01       17        2     0     2   0               2   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
216               2              4             11

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
224 2018-01-13        2        7     4     0   2               1   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
224               0             12              7

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
249 2018-01-31        2        1     2     0   2               1   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
249               2             13             16

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
264 2018-10-02        2        5     1     0   2               1   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
264               2             14             13

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
277 2018-02-25       10        2     0     1   0               0   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
277               2              6             15

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
285 2018-03-03        2       15     2     0   2               2   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
285               2             16              8

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
298 2018-11-03       11        2     1     4   0               1   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
298               2              8             17

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
313 2018-01-04        4        2     1     3   0               2   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
313               2             17             18

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
319 2018-07-04       18        2     1     2   0               0   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
319               2              6             19

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
330 2018-04-14        2        0     1     3   0               2   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
330               0             20             27

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
353 2018-04-30        2       13     2     0   2               1   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
353               1             20             10

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
360 2018-05-05       19        2     1     0   2               2   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
360               2              5             21

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
368 2018-09-05        2        9     1     0   2               0   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
368               0             21             11

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
378 2018-05-13        2        8     5     4   2               2   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
378               2             22             12

In [12]:
X_train, X_test, y_train, y_test = train_test_split(dataset[feature_names].values, dataset['FTR'].values, shuffle=False, random_state = 5)
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

X_train = X_train.astype('int')
y_train = y_train.astype('int')
X_test = X_test.astype('int')
y_test = y_test.astype('int')

X_train shape: (285, 6)
y_train shape: (285,)


In [13]:
y_train

array([2, 0, 0, 0, 2, 1, 1, 2, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 1, 0, 0,
       1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 0, 2, 2, 0, 1, 1,
       2, 1, 0, 1, 1, 2, 1, 2, 0, 2, 0, 0, 0, 0, 2, 2, 1, 0, 0, 2, 2, 1,
       2, 2, 0, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 0, 2, 2, 2, 2, 2, 0, 0,
       0, 2, 2, 0, 1, 2, 2, 0, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2, 2, 2, 2,
       2, 2, 2, 1, 0, 2, 2, 0, 2, 1, 1, 2, 1, 2, 0, 1, 1, 0, 0, 2, 1, 2,
       0, 1, 2, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 0,
       2, 2, 2, 1, 0, 1, 2, 2, 0, 1, 2, 0, 0, 0, 2, 1, 2, 1, 2, 0, 2, 0,
       0, 0, 0, 2, 1, 2, 0, 1, 1, 2, 1, 2, 1, 0, 1, 2, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 1, 2, 1, 1, 0, 1, 1, 1, 0, 0, 2, 0, 2, 0, 0, 2, 1, 1,
       1, 2, 0, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2, 2, 2, 1, 1, 2, 0, 2,
       1, 0, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 0, 1, 1, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 0, 2, 1, 2, 1, 1, 2, 2, 0, 0, 2, 0, 2, 1, 2, 1, 2])

In [14]:
knn = KNeighborsClassifier(n_neighbors=69)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [15]:
y_pred

array([2, 2, 0, 2, 0, 2, 2, 1, 2, 2, 0, 0, 2, 0, 0, 2, 1, 2, 0, 0, 0, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2, 0,
       0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2, 1, 0,
       2, 0, 2, 0, 2, 2, 2, 1, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 0,
       2, 2, 2, 0, 1, 2, 0])

In [16]:
y_test

array([2, 2, 2, 2, 0, 2, 2, 1, 2, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0,
       2, 2, 1, 0, 2, 2, 0, 1, 1, 1, 0, 0, 0, 0, 1, 2, 1, 2, 2, 2, 2, 0,
       1, 0, 0, 2, 1, 1, 0, 0, 1, 1, 1, 2, 2, 1, 2, 1, 2, 0, 1, 0, 2, 0,
       2, 0, 2, 2, 2, 1, 0, 0, 2, 2, 2, 2, 1, 0, 1, 2, 2, 2, 1, 0, 2, 0,
       2, 2, 2, 0, 0, 2, 2])

In [17]:
#print("Test set predictions:\n", y_pred)
# Using the team names, both team's last result AND how many wins both teams currently have.
print("Test set score:  {:.2f}".format(np.mean(y_pred == y_test)))

Test set score:  0.61


# New Feature: Previous season rank?

In [18]:
standings = pd.read_csv("Files\epl20162017.csv")
feature_names.append("HomeTeamRanksHigher")
standings

Rank               Team  MP   W   D   L   F   A  D.1   P
0      1            Chelsea  38  30   3   5  85  33   52  93
1      2  Tottenham Hotspur  38  26   8   4  86  26   60  86
2      3    Manchester City  38  23   9   6  80  39   41  78
3      4          Liverpool  38  22  10   6  78  42   36  76
4      5            Arsenal  38  23   6   9  77  44   33  75
5      6  Manchester United  38  18  15   5  54  29   25  69
6      7            Everton  38  17  10  11  62  44   18  61
7      8        Southampton  38  12  10  16  41  48   -7  46
8      9        Bournemouth  38  12  10  16  55  67  -12  46
9     10          West Brom  38  12   9  17  43  51   -8  45
10    11           West Ham  38  12   9  17  47  64  -17  45
11    12     Leicester City  38  12   8  18  48  63  -15  44
12    13         Stoke City  38  11  11  16  41  56  -15  44
13    14     Crystal Palace  38  12   5  21  50  63  -13  41
14    15            Swansea  38  12   5  21  45  70  -25  41
15    16            Burnley  38  11   7  20  39  55  -16  40
16    17            Watford  38  11   7  20  40  68  -28  40
17    18          Hull City  38   9   7  22  37  80  -43  34
18    19      Middlesbrough  38   5  13  20  27  53  -26  28
19    20         Sunderland  38   6   6  26  29  69  -40  24

In [19]:
dataset

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
0   2017-11-08        5        8     4     3   2              -1   
1   2017-12-08       14        0     0     2   0              -1   
2   2017-12-08        4        6     2     3   0              -1   
3   2017-12-08       10       15     0     3   0              -1   
4   2017-12-08        7       18     1     0   2              -1   
..         ...      ...      ...   ...   ...  ..             ...   
375 2018-05-13        9        4     3     0   2               0   
376 2018-05-13       16        0     0     1   0               2   
377 2018-05-13       17       18     1     2   0               0   
378 2018-05-13        2        8     5     4   2               2   
379 2018-05-13       12        7     3     1   2               1   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  
0                -1              0              0  
1                -1              0              0  
2                -1              0              0  
3                -1              0              0  
4                -1              0              0  
..              ...            ...            ...  
375               1             11             21  
376               2              7             31  
377               0              8              6  
378               2             22             12  
379               1              9             13  

[380 rows x 10 columns]

In [20]:
# list out keys and values seperately from our "team_names" dictionary

key_list = list(team_names.keys())
val_list = list(team_names.values())

In [21]:
for index, row in standings.iterrows():
    team = row["Team"]   
    if team == "Hull City":
        row['Team'] = "Newcastle"  
    if team == "Middlesbrough":
        row['Team'] = "Brighton"    
    if team == "Sunderland":
        row['Team'] = "Huddersfield"
    
    standings.iloc[index] = row
standings

Rank               Team  MP   W   D   L   F   A  D.1   P
0      1            Chelsea  38  30   3   5  85  33   52  93
1      2  Tottenham Hotspur  38  26   8   4  86  26   60  86
2      3    Manchester City  38  23   9   6  80  39   41  78
3      4          Liverpool  38  22  10   6  78  42   36  76
4      5            Arsenal  38  23   6   9  77  44   33  75
5      6  Manchester United  38  18  15   5  54  29   25  69
6      7            Everton  38  17  10  11  62  44   18  61
7      8        Southampton  38  12  10  16  41  48   -7  46
8      9        Bournemouth  38  12  10  16  55  67  -12  46
9     10          West Brom  38  12   9  17  43  51   -8  45
10    11           West Ham  38  12   9  17  47  64  -17  45
11    12     Leicester City  38  12   8  18  48  63  -15  44
12    13         Stoke City  38  11  11  16  41  56  -15  44
13    14     Crystal Palace  38  12   5  21  50  63  -13  41
14    15            Swansea  38  12   5  21  45  70  -25  41
15    16            Burnley  38  11   7  20  39  55  -16  40
16    17            Watford  38  11   7  20  40  68  -28  40
17    18          Newcastle  38   9   7  22  37  80  -43  34
18    19           Brighton  38   5  13  20  27  53  -26  28
19    20       Huddersfield  38   6   6  26  29  69  -40  24

In [22]:
# Encode our standings dataset in order to make comparisons with our main dataset

for index, row in standings.iterrows():
    currentTeam = row["Team"]
    for key, value in team_names.items():
        if key == currentTeam:
            row['Team'] = value
            print(currentTeam)
            print(row['Team'])
            standings.iloc[index] = row
standings

Chelsea
4
Tottenham Hotspur
2
Manchester City
0
Liverpool
3
Arsenal
5
Manchester United
1
Everton
7
Southampton
16
Bournemouth
11
West Brom
19
West Ham
12
Leicester City
8
Stoke City
18
Crystal Palace
10
Swansea
17
Burnley
6
Watford
13
Newcastle
9
Brighton
14
Huddersfield
15


Rank Team  MP   W   D   L   F   A  D.1   P
0      1    4  38  30   3   5  85  33   52  93
1      2    2  38  26   8   4  86  26   60  86
2      3    0  38  23   9   6  80  39   41  78
3      4    3  38  22  10   6  78  42   36  76
4      5    5  38  23   6   9  77  44   33  75
5      6    1  38  18  15   5  54  29   25  69
6      7    7  38  17  10  11  62  44   18  61
7      8   16  38  12  10  16  41  48   -7  46
8      9   11  38  12  10  16  55  67  -12  46
9     10   19  38  12   9  17  43  51   -8  45
10    11   12  38  12   9  17  47  64  -17  45
11    12    8  38  12   8  18  48  63  -15  44
12    13   18  38  11  11  16  41  56  -15  44
13    14   10  38  12   5  21  50  63  -13  41
14    15   17  38  12   5  21  45  70  -25  41
15    16    6  38  11   7  20  39  55  -16  40
16    17   13  38  11   7  20  40  68  -28  40
17    18    9  38   9   7  22  37  80  -43  34
18    19   14  38   5  13  20  27  53  -26  28
19    20   15  38   6   6  26  29  69  -40  24

In [23]:
dataset['HomeTeamRanksHigher'] = 0
for index, row in dataset.iterrows():
    home_team = row["HomeTeam"]
    away_team = row["AwayTeam"]
                    
    home_rank = standings[standings["Team"] == home_team]["Rank"].values[0]
    print("Home rank: ", home_rank)
    away_rank = standings[standings["Team"] == away_team]["Rank"].values[0]
    print("Away rank: ", away_rank)
    row['HomeTeamRanksHigher'] = int(home_rank > away_rank)
    dataset.iloc[index] = row

Home rank:  5
Away rank:  12
Home rank:  19
Away rank:  3
Home rank:  1
Away rank:  16
Home rank:  14
Away rank:  20
Home rank:  7
Away rank:  13
Home rank:  8
Away rank:  15
Home rank:  17
Away rank:  4
Home rank:  10
Away rank:  9
Home rank:  6
Away rank:  11
Home rank:  18
Away rank:  2
Home rank:  9
Away rank:  17
Home rank:  16
Away rank:  10
Home rank:  12
Away rank:  19
Home rank:  4
Away rank:  14
Home rank:  8
Away rank:  11
Home rank:  13
Away rank:  5
Home rank:  15
Away rank:  6
Home rank:  20
Away rank:  18
Home rank:  2
Away rank:  1
Home rank:  3
Away rank:  7
Home rank:  9
Away rank:  3
Home rank:  14
Away rank:  15
Home rank:  20
Away rank:  8
Home rank:  6
Away rank:  12
Home rank:  18
Away rank:  11
Home rank:  17
Away rank:  19
Home rank:  1
Away rank:  7
Home rank:  4
Away rank:  5
Home rank:  2
Away rank:  16
Home rank:  10
Away rank:  13
Home rank:  5
Away rank:  9
Home rank:  19
Away rank:  10
Home rank:  7
Away rank:  2
Home rank:  12
Away rank:  1
Home rank:  

Home rank:  8
Away rank:  13
Home rank:  15
Away rank:  11
Home rank:  2
Away rank:  20
Home rank:  17
Away rank:  10
Home rank:  19
Away rank:  5
Home rank:  3
Away rank:  1
Home rank:  14
Away rank:  6
Home rank:  1
Away rank:  14
Home rank:  7
Away rank:  19
Home rank:  20
Away rank:  15
Home rank:  6
Away rank:  4
Home rank:  18
Away rank:  8
Home rank:  10
Away rank:  12
Home rank:  11
Away rank:  16
Home rank:  5
Away rank:  17
Home rank:  9
Away rank:  2
Home rank:  13
Away rank:  3
Home rank:  9
Away rank:  10
Home rank:  20
Away rank:  14
Home rank:  4
Away rank:  17
Home rank:  13
Away rank:  7
Home rank:  19
Away rank:  12
Home rank:  14
Away rank:  4
Home rank:  7
Away rank:  3
Home rank:  6
Away rank:  15
Home rank:  18
Away rank:  20
Home rank:  17
Away rank:  9
Home rank:  10
Away rank:  16
Home rank:  11
Away rank:  8
Home rank:  5
Away rank:  13
Home rank:  1
Away rank:  2
Home rank:  9
Away rank:  14
Home rank:  19
Away rank:  20
Home rank:  7
Away rank:  4
Home rank:

In [24]:
dataset

Date HomeTeam AwayTeam  FTHG  FTAG FTR  HomeLastResult  \
0   2017-11-08        5        8     4     3   2              -1   
1   2017-12-08       14        0     0     2   0              -1   
2   2017-12-08        4        6     2     3   0              -1   
3   2017-12-08       10       15     0     3   0              -1   
4   2017-12-08        7       18     1     0   2              -1   
..         ...      ...      ...   ...   ...  ..             ...   
375 2018-05-13        9        4     3     0   2               0   
376 2018-05-13       16        0     0     1   0               2   
377 2018-05-13       17       18     1     2   0               0   
378 2018-05-13        2        8     5     4   2               2   
379 2018-05-13       12        7     3     1   2               1   

     AwayLastResult  HomeWinsSoFar  AwayWinsSoFar  HomeTeamRanksHigher  
0                -1              0              0                    0  
1                -1              0              0                    1  
2                -1              0              0                    0  
3                -1              0              0                    0  
4                -1              0              0                    0  
..              ...            ...            ...                  ...  
375               1             11             21                    1  
376               2              7             31                    1  
377               0              8              6                    1  
378               2             22             12                    0  
379               1              9             13                    1  

[380 rows x 11 columns]

In [25]:
feature_names

['HomeTeam',
 'AwayTeam',
 'HomeLastResult',
 'AwayLastResult',
 'HomeWinsSoFar',
 'AwayWinsSoFar',
 'HomeTeamRanksHigher']

In [26]:
feature_names.pop(2)
feature_names.pop(2)
#feature_names.pop(2)
#feature_names.pop(2)
#feature_names.pop(0)
#feature_names.pop(0)


X_train, X_test, y_train, y_test = train_test_split(dataset[feature_names].values, dataset['FTR'].values, shuffle=False, random_state = 5)
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

X_train = X_train.astype('int')
y_train = y_train.astype('int')
X_test = X_test.astype('int')
y_test = y_test.astype('int')

X_train shape: (285, 5)
y_train shape: (285,)


In [27]:
X_train

array([[ 5,  8,  0,  0,  0],
       [14,  0,  0,  0,  1],
       [ 4,  6,  0,  0,  0],
       ...,
       [ 3,  9, 16,  7,  0],
       [16, 18,  5,  6,  0],
       [17, 12,  7,  7,  1]])

In [28]:
feature_names

['HomeTeam',
 'AwayTeam',
 'HomeWinsSoFar',
 'AwayWinsSoFar',
 'HomeTeamRanksHigher']

In [29]:
knn = KNeighborsClassifier(n_neighbors=71)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
# Using team names, how many wins each team has so far and which team ranked higher last season.
print("Test set score:  {:.2f}%".format(np.mean(y_pred == y_test) * 100))

Test set score:  62.11%


# Random Forest?

In [30]:

feature_names = ['HomeTeam',
 'AwayTeam',
 'HomeLastResult',
 'AwayLastResult',
 'HomeTeamRanksHigher']

In [31]:
from sklearn.ensemble import RandomForestClassifier


clf = RandomForestClassifier(random_state=5, n_estimators=36 )
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Test set score:  {:.2f}".format(np.mean(y_pred == y_test)))
print('Score: ', clf.oob_score)

Test set score:  0.51
Score:  False


In [32]:
y_pred = clf.predict(X_test)

In [33]:
print("Test set score:  {:.2f}".format(np.mean(y_pred == y_test)))

Test set score:  0.51


# Neural Network

In [34]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report

mlpc=MLPClassifier(hidden_layer_sizes=(11,11,11),max_iter=500)
mlpc.fit(X_train, y_train)
predict_mlpc = mlpc.predict(X_test)
print("Test set score:  {:.2f}".format(np.mean(predict_mlpc == y_test)))

Test set score:  0.49


C:\Users\WillyB\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [35]:
print(classification_report(y_test, predict_mlpc))
print(confusion_matrix(y_test, predict_mlpc))


              precision    recall  f1-score   support

           0       0.62      0.25      0.36        32
           1       0.24      0.35      0.29        20
           2       0.60      0.74      0.67        43

    accuracy                           0.49        95
   macro avg       0.49      0.45      0.44        95
weighted avg       0.53      0.49      0.48        95

[[ 8 13 11]
 [ 3  7 10]
 [ 2  9 32]]


In [36]:
print(classification_report(y_test, predict_mlpc))

              precision    recall  f1-score   support

           0       0.62      0.25      0.36        32
           1       0.24      0.35      0.29        20
           2       0.60      0.74      0.67        43

    accuracy                           0.49        95
   macro avg       0.49      0.45      0.44        95
weighted avg       0.53      0.49      0.48        95



In [37]:
print(confusion_matrix(y_test, predict_mlpc))

[[ 8 13 11]
 [ 3  7 10]
 [ 2  9 32]]
